# Generated by Django 5.0.4 on 2024-07-16 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='position',
        ),
    ]
