# Generated by Django 5.0.4 on 2024-05-10 07:38

import django.db.models.deletion
import main.utils
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property_name', models.CharField(max_length=100)),
                ('property_photo', models.ImageField(upload_to=main.utils.user_property_directory_path)),
                ('property_location', models.CharField(max_length=100)),
                ('year_built', models.DateField()),
                ('price', models.CharField(max_length=20)),
                ('garages', models.BigIntegerField()),
                ('plot_size', models.CharField(max_length=200)),
                ('area', models.CharField(max_length=200)),
                ('bathroom', models.CharField(max_length=20)),
                ('bedroom', models.CharField(max_length=20)),
                ('color', models.CharField(default='White', max_length=24)),
                ('description', models.TextField()),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
            ],
        ),
    ]
