# Generated by Django 5.0.4 on 2024-07-12 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_likedlisting'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='is_sold',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False),
        ),
        migrations.CreateModel(
            name='PurchasedProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_name', models.CharField(max_length=100)),
                ('property_type', models.CharField(choices=[('Land', 'Land'), ('House', 'House')], max_length=5)),
                ('house_type', models.CharField(blank=True, max_length=50, null=True)),
                ('city', models.CharField(db_index=True, max_length=100)),
                ('size', models.DecimalField(decimal_places=2, max_digits=10)),
                ('size_unit', models.CharField(max_length=20)),
                ('purchase_date', models.DateField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
            options={
                'verbose_name_plural': 'Properties',
                'indexes': [models.Index(fields=['purchase_date'], name='purchase_date_idx')],
            },
        ),
    ]
