# Generated by Django 5.0.4 on 2025-04-02 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_negotiation'),
    ]

    operations = [
        migrations.AddField(
            model_name='negotiation',
            name='proposed_amount',
            field=models.IntegerField(max_length=100, null=True),
        ),
    ]
